snowflake_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      database: SUPABASE_DEV
      role: DBT_DEV_ROLE
      schema: PUBLIC
      warehouse: SUPABASE_DEV_WH
      threads: 4

    sit:
      type: snowflake
      database: SUPABASE_SIT
      role: DBT_SIT_ROLE
      schema: PUBLIC
      warehouse: SUPABASE_SIT_WH
      threads: 4

    uat:
      type: snowflake
      database: SUPABASE_UAT
      role: DBT_UAT_ROLE
      schema: PUBLIC
      warehouse: SUPABASE_UAT_WH
      threads: 4

    prod:
      type: snowflake
      database: SUPABASE_PROD
      role: DBT_PROD_ROLE
      schema: PUBLIC
      warehouse: SUPABASE_PROD_WH
      threads: 8
