snowflake_profile:
  target: snowflake
  outputs:
    snowflake:
      type: snowflake
      account: IKJUREX-GV64642
      user: ARINDHIMAR
      private_key_path: /home/user/rsa_key.p8
      role: ACCOUNTADMIN
      database: SOLVEFINS_DATA_V2
      warehouse: COMPUTE_WH
      schema: PUBLIC
      threads: 4
