name: dbt CI — PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [dev, sit, uat, main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  pr-validate:
    name: "PR Validation"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt-snowflake
        run: pip install dbt-snowflake==1.9.0

      - name: Setup RSA Key
        env:
          PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_DEV }}
        run: |
          printf '%s' "$PRIVATE_KEY" | tr -d '\r' > /tmp/sf_key.p8
          chmod 600 /tmp/sf_key.p8

      - name: Verifying Packages using dbt deps
        run: dbt deps

      - name: Verifying Syntax, Jinja, DAG , refs using dbt parse
        run: dbt parse

      - name: Verifying Model SQL Compilation using dbt compile
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: "SVC_DBT_DEV"
          SNOWFLAKE_ROLE: "DBT_DEV_ROLE"
          SNOWFLAKE_WAREHOUSE: "SUPABASE_DEV_WH"
          SNOWFLAKE_DATABASE: "SUPABASE_DEV"
          SNOWFLAKE_PRIVATE_KEY_PATH: "/tmp/sf_key.p8"
        run: dbt compile --target dev
